name: events_project_workflows

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
    - main
    - develop
    - releases/**

jobs:
  check-bats-version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Run test
        run: npm run test

      - name: Run the Build
        run: |
          npm install
          npm run devstart

      - name: Deploy to Heroku
        run: git push Heroku main
