name: events_project_workflows

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
    - main
    - develop
    - releases/**

jobs:
  test_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Run the test & Build
        run: |
          npm install
          npm run devstart
          npm run test


      - name: Deploy to Heroku
        run: git push Heroku main
